server:
  port: 8082
  tomcat:
    max-http-form-post-size: 10GB

spring:
  application:
    name: mytrip

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytrip?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: mytrip
    password: fullstack2409

# MyBatis 매퍼(mapper) 파일 위치 설정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.lec.spring.mytrip.domain

logging:
  level:
    root: INFO
    org.mybatis: DEBUG